/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'mentor' : IDL.Text,
  'username' : IDL.Text,
  'mode' : IDL.Text,
  'password' : IDL.Text,
  'email' : IDL.Text,
  'language' : IDL.Text,
  'wakeWord' : IDL.Text,
  'conversationMemory' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearConversationMemory' : IDL.Func([], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationMemory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveConversationEntry' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setLanguage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setMentor' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setMode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setWakeWord' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'mentor' : IDL.Text,
    'username' : IDL.Text,
    'mode' : IDL.Text,
    'password' : IDL.Text,
    'email' : IDL.Text,
    'language' : IDL.Text,
    'wakeWord' : IDL.Text,
    'conversationMemory' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearConversationMemory' : IDL.Func([], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationMemory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveConversationEntry' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setLanguage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setMentor' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setMode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setWakeWord' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };